package com.savio.rentaroom.banco;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ALUNO_SIGAA".
 */
public class AlunoSigaa {

    private String codigo;
    private String nome;
    private String cpf;

    public AlunoSigaa() {
    }

    public AlunoSigaa(String codigo) {
        this.codigo = codigo;
    }

    public AlunoSigaa(String codigo, String nome, String cpf) {
        this.codigo = codigo;
        this.nome = nome;
        this.cpf = cpf;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getCpf() {
        return cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

}
