package com.savio.rentaroom.banco;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CALENDARIO".
 */
public class Calendario {

    private Long id;
    private java.util.Date hora;
    private java.util.Date dia;
    private java.util.Date mes;
    private java.util.Date ano;
    private String sala_id;

    public Calendario() {
    }

    public Calendario(Long id) {
        this.id = id;
    }

    public Calendario(Long id, java.util.Date hora, java.util.Date dia, java.util.Date mes, java.util.Date ano, String sala_id) {
        this.id = id;
        this.hora = hora;
        this.dia = dia;
        this.mes = mes;
        this.ano = ano;
        this.sala_id = sala_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getHora() {
        return hora;
    }

    public void setHora(java.util.Date hora) {
        this.hora = hora;
    }

    public java.util.Date getDia() {
        return dia;
    }

    public void setDia(java.util.Date dia) {
        this.dia = dia;
    }

    public java.util.Date getMes() {
        return mes;
    }

    public void setMes(java.util.Date mes) {
        this.mes = mes;
    }

    public java.util.Date getAno() {
        return ano;
    }

    public void setAno(java.util.Date ano) {
        this.ano = ano;
    }

    public String getSala_id() {
        return sala_id;
    }

    public void setSala_id(String sala_id) {
        this.sala_id = sala_id;
    }

}
