package com.savio.rentaroom.banco;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.savio.rentaroom.banco.Centro;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CENTRO".
*/
public class CentroDao extends AbstractDao<Centro, String> {

    public static final String TABLENAME = "CENTRO";

    /**
     * Properties of entity Centro.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Nome = new Property(0, String.class, "nome", true, "NOME");
        public final static Property Telefone = new Property(1, String.class, "telefone", false, "TELEFONE");
        public final static Property Localizacao = new Property(2, String.class, "localizacao", false, "LOCALIZACAO");
    };

    private DaoSession daoSession;


    public CentroDao(DaoConfig config) {
        super(config);
    }
    
    public CentroDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CENTRO\" (" + //
                "\"NOME\" TEXT PRIMARY KEY NOT NULL UNIQUE ," + // 0: nome
                "\"TELEFONE\" TEXT," + // 1: telefone
                "\"LOCALIZACAO\" TEXT);"); // 2: localizacao
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CENTRO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Centro entity) {
        stmt.clearBindings();
 
        String nome = entity.getNome();
        if (nome != null) {
            stmt.bindString(1, nome);
        }
 
        String telefone = entity.getTelefone();
        if (telefone != null) {
            stmt.bindString(2, telefone);
        }
 
        String localizacao = entity.getLocalizacao();
        if (localizacao != null) {
            stmt.bindString(3, localizacao);
        }
    }

    @Override
    protected void attachEntity(Centro entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Centro readEntity(Cursor cursor, int offset) {
        Centro entity = new Centro( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // nome
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // telefone
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // localizacao
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Centro entity, int offset) {
        entity.setNome(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTelefone(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLocalizacao(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(Centro entity, long rowId) {
        return entity.getNome();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(Centro entity) {
        if(entity != null) {
            return entity.getNome();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
