package com.savio.rentaroom.banco;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.savio.rentaroom.banco.Gerente;
import com.savio.rentaroom.banco.Centro;
import com.savio.rentaroom.banco.Departamento;
import com.savio.rentaroom.banco.Aluga;
import com.savio.rentaroom.banco.Sala;
import com.savio.rentaroom.banco.Professor;
import com.savio.rentaroom.banco.Aluno;
import com.savio.rentaroom.banco.Funcionario;
import com.savio.rentaroom.banco.ProfessorSigaa;
import com.savio.rentaroom.banco.FuncionarioSigaa;
import com.savio.rentaroom.banco.AlunoSigaa;

import com.savio.rentaroom.banco.GerenteDao;
import com.savio.rentaroom.banco.CentroDao;
import com.savio.rentaroom.banco.DepartamentoDao;
import com.savio.rentaroom.banco.AlugaDao;
import com.savio.rentaroom.banco.SalaDao;
import com.savio.rentaroom.banco.ProfessorDao;
import com.savio.rentaroom.banco.AlunoDao;
import com.savio.rentaroom.banco.FuncionarioDao;
import com.savio.rentaroom.banco.ProfessorSigaaDao;
import com.savio.rentaroom.banco.FuncionarioSigaaDao;
import com.savio.rentaroom.banco.AlunoSigaaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gerenteDaoConfig;
    private final DaoConfig centroDaoConfig;
    private final DaoConfig departamentoDaoConfig;
    private final DaoConfig alugaDaoConfig;
    private final DaoConfig salaDaoConfig;
    private final DaoConfig professorDaoConfig;
    private final DaoConfig alunoDaoConfig;
    private final DaoConfig funcionarioDaoConfig;
    private final DaoConfig professorSigaaDaoConfig;
    private final DaoConfig funcionarioSigaaDaoConfig;
    private final DaoConfig alunoSigaaDaoConfig;

    private final GerenteDao gerenteDao;
    private final CentroDao centroDao;
    private final DepartamentoDao departamentoDao;
    private final AlugaDao alugaDao;
    private final SalaDao salaDao;
    private final ProfessorDao professorDao;
    private final AlunoDao alunoDao;
    private final FuncionarioDao funcionarioDao;
    private final ProfessorSigaaDao professorSigaaDao;
    private final FuncionarioSigaaDao funcionarioSigaaDao;
    private final AlunoSigaaDao alunoSigaaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gerenteDaoConfig = daoConfigMap.get(GerenteDao.class).clone();
        gerenteDaoConfig.initIdentityScope(type);

        centroDaoConfig = daoConfigMap.get(CentroDao.class).clone();
        centroDaoConfig.initIdentityScope(type);

        departamentoDaoConfig = daoConfigMap.get(DepartamentoDao.class).clone();
        departamentoDaoConfig.initIdentityScope(type);

        alugaDaoConfig = daoConfigMap.get(AlugaDao.class).clone();
        alugaDaoConfig.initIdentityScope(type);

        salaDaoConfig = daoConfigMap.get(SalaDao.class).clone();
        salaDaoConfig.initIdentityScope(type);

        professorDaoConfig = daoConfigMap.get(ProfessorDao.class).clone();
        professorDaoConfig.initIdentityScope(type);

        alunoDaoConfig = daoConfigMap.get(AlunoDao.class).clone();
        alunoDaoConfig.initIdentityScope(type);

        funcionarioDaoConfig = daoConfigMap.get(FuncionarioDao.class).clone();
        funcionarioDaoConfig.initIdentityScope(type);

        professorSigaaDaoConfig = daoConfigMap.get(ProfessorSigaaDao.class).clone();
        professorSigaaDaoConfig.initIdentityScope(type);

        funcionarioSigaaDaoConfig = daoConfigMap.get(FuncionarioSigaaDao.class).clone();
        funcionarioSigaaDaoConfig.initIdentityScope(type);

        alunoSigaaDaoConfig = daoConfigMap.get(AlunoSigaaDao.class).clone();
        alunoSigaaDaoConfig.initIdentityScope(type);

        gerenteDao = new GerenteDao(gerenteDaoConfig, this);
        centroDao = new CentroDao(centroDaoConfig, this);
        departamentoDao = new DepartamentoDao(departamentoDaoConfig, this);
        alugaDao = new AlugaDao(alugaDaoConfig, this);
        salaDao = new SalaDao(salaDaoConfig, this);
        professorDao = new ProfessorDao(professorDaoConfig, this);
        alunoDao = new AlunoDao(alunoDaoConfig, this);
        funcionarioDao = new FuncionarioDao(funcionarioDaoConfig, this);
        professorSigaaDao = new ProfessorSigaaDao(professorSigaaDaoConfig, this);
        funcionarioSigaaDao = new FuncionarioSigaaDao(funcionarioSigaaDaoConfig, this);
        alunoSigaaDao = new AlunoSigaaDao(alunoSigaaDaoConfig, this);

        registerDao(Gerente.class, gerenteDao);
        registerDao(Centro.class, centroDao);
        registerDao(Departamento.class, departamentoDao);
        registerDao(Aluga.class, alugaDao);
        registerDao(Sala.class, salaDao);
        registerDao(Professor.class, professorDao);
        registerDao(Aluno.class, alunoDao);
        registerDao(Funcionario.class, funcionarioDao);
        registerDao(ProfessorSigaa.class, professorSigaaDao);
        registerDao(FuncionarioSigaa.class, funcionarioSigaaDao);
        registerDao(AlunoSigaa.class, alunoSigaaDao);
    }
    
    public void clear() {
        gerenteDaoConfig.getIdentityScope().clear();
        centroDaoConfig.getIdentityScope().clear();
        departamentoDaoConfig.getIdentityScope().clear();
        alugaDaoConfig.getIdentityScope().clear();
        salaDaoConfig.getIdentityScope().clear();
        professorDaoConfig.getIdentityScope().clear();
        alunoDaoConfig.getIdentityScope().clear();
        funcionarioDaoConfig.getIdentityScope().clear();
        professorSigaaDaoConfig.getIdentityScope().clear();
        funcionarioSigaaDaoConfig.getIdentityScope().clear();
        alunoSigaaDaoConfig.getIdentityScope().clear();
    }

    public GerenteDao getGerenteDao() {
        return gerenteDao;
    }

    public CentroDao getCentroDao() {
        return centroDao;
    }

    public DepartamentoDao getDepartamentoDao() {
        return departamentoDao;
    }

    public AlugaDao getAlugaDao() {
        return alugaDao;
    }

    public SalaDao getSalaDao() {
        return salaDao;
    }

    public ProfessorDao getProfessorDao() {
        return professorDao;
    }

    public AlunoDao getAlunoDao() {
        return alunoDao;
    }

    public FuncionarioDao getFuncionarioDao() {
        return funcionarioDao;
    }

    public ProfessorSigaaDao getProfessorSigaaDao() {
        return professorSigaaDao;
    }

    public FuncionarioSigaaDao getFuncionarioSigaaDao() {
        return funcionarioSigaaDao;
    }

    public AlunoSigaaDao getAlunoSigaaDao() {
        return alunoSigaaDao;
    }

}
