package com.savio.rentaroom.banco;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.savio.rentaroom.banco.Gerente;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GERENTE".
*/
public class GerenteDao extends AbstractDao<Gerente, String> {

    public static final String TABLENAME = "GERENTE";

    /**
     * Properties of entity Gerente.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Login = new Property(0, String.class, "login", true, "LOGIN");
        public final static Property Senha = new Property(1, String.class, "senha", false, "SENHA");
    };


    public GerenteDao(DaoConfig config) {
        super(config);
    }
    
    public GerenteDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GERENTE\" (" + //
                "\"LOGIN\" TEXT PRIMARY KEY NOT NULL UNIQUE ," + // 0: login
                "\"SENHA\" TEXT);"); // 1: senha
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GERENTE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Gerente entity) {
        stmt.clearBindings();
 
        String login = entity.getLogin();
        if (login != null) {
            stmt.bindString(1, login);
        }
 
        String senha = entity.getSenha();
        if (senha != null) {
            stmt.bindString(2, senha);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Gerente readEntity(Cursor cursor, int offset) {
        Gerente entity = new Gerente( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // login
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // senha
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Gerente entity, int offset) {
        entity.setLogin(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setSenha(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(Gerente entity, long rowId) {
        return entity.getLogin();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(Gerente entity) {
        if(entity != null) {
            return entity.getLogin();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
